CITYS = [
  "alingsås",
  "arboga",
  "arvika",
  "askersund",
  "avesta",
  "boden",
  "bollnäs",
  "borgholm",
  "borlänge",
  "borås",
  "vänersborgs stad",
  "båstad",
  "kristianstads län",
  "djursholm ",
  "eksjö",
  "enköping",
  "eskilstuna",
  "eslöv",
  "fagersta",
  "falkenberg",
  "falköping",
  "skanör med falsterbo stad",
  "falun",
  "filipstad",
  "flen",
  "gränna",
  "gävle",
  "göteborg",
  "hagfors",
  "halmstad",
  "haparanda",
  "hedemora",
  "helsingborg",
  "hjo",
  "hudiksvall",
  "huskvarna",
  "härnösand",
  "hässleholm",
  "kristianstads län",
  "höganäs",
  "jönköping",
  "kalmar",
  "karl johans stad",
  "karlshamn",
  "karlskoga",
  "karlskrona",
  "karlstad",
  "katrineholm",
  "kiruna",
  "kramfors",
  "kristianstad",
  "kristianstads län",
  "kristinehamn",
  "kumla",
  "kungsbacka",
  "kungälv",
  "köping",
  "laholm",
  "landskrona",
  "lidingö",
  "lidköping",
  "lindesberg",
  "linköping",
  "ljungby",
  "ludvika",
  "luleå",
  "lund",
  "kristianstads län",
  "lycksele",
  "lysekil",
  "malmö",
  "mariefred",
  "mariestad",
  "marstrand",
  "mjölby",
  "motala",
  "mölndal",
  "mönsterås",
  "nacka",
  "nora",
  "norrköping",
  "norrtälje",
  "nybro",
  "nyköping",
  "nynäshamn",
  "nässjö",
  "oskarshamn",
  "oxelösund",
  "piteå",
  "ronneby",
  "sala",
  "sandviken",
  "sigtuna",
  "simrishamn",
  "kristianstads län",
  "skanör med falsterbo stad",
  "skanör med falsterbo",
  "skara",
  "skellefteå",
  "skänninge",
  "skövde",
  "sollefteå",
  "solna",
  "stockholm",
  "strängnäs",
  "strömstad",
  "sundbyberg",
  "sundsvall",
  "säffle",
  "säter",
  "sävsjö",
  "söderhamn",
  "söderköping",
  "södertälje",
  "sölvesborg",
  "tidaholm",
  "torget",
  "torshälla",
  "tranås",
  "trelleborg",
  "trollhättan",
  "trosa",
  "kristianstads län",
  "uddevalla",
  "ulricehamn",
  "umeå",
  "uppsala",
  "vadstena",
  "varberg",
  "vaxholm",
  "vetlanda",
  "vimmerby",
  "visby",
  "kristianstads län",
  "kristianstads kommun",
  "vänersborg",
  "värnamo",
  "västervik",
  "västerås",
  "växjö",
  "ystad",
  "kristianstads län",
  "kristianstads kommun",
  "åmål",
  "älvsborg",
  "ängelholm",
  "kristianstads län",
  "örebro",
  "öregrund",
  "örnsköldsvik",
  "östersund",
  "östhammar"
]

BLACKLIST = ["svenska", "engelska", "can", "design", "data", "förvaltning", "verktyg", "högskoleutbildning", "eftergymnasial utbildning", "kommunikation", "problemlösning", "tekniker", "general", "manager", "major", "mentor"]
