CITYS = [
  "alingsås",
  "arboga",
  "arvika",
  "askersund",
  "avesta",
  "boden",
  "bollnäs",
  "borgholm",
  "borlänge",
  "borås",
  "vänersborgs stad",
  "båstad",
  "kristianstads län",
  "djursholm ",
  "eksjö",
  "enköping",
  "eskilstuna",
  "eslöv",
  "fagersta",
  "falkenberg",
  "falköping",
  "skanör med falsterbo stad",
  "falun",
  "filipstad",
  "flen",
  "gränna",
  "gävle",
  "göteborg",
  "hagfors",
  "halmstad",
  "haparanda",
  "hedemora",
  "helsingborg",
  "hjo",
  "hudiksvall",
  "huskvarna",
  "härnösand",
  "hässleholm",
  "kristianstads län",
  "höganäs",
  "jönköping",
  "kalmar",
  "karl johans stad",
  "karlshamn",
  "karlskoga",
  "karlskrona",
  "karlstad",
  "katrineholm",
  "kiruna",
  "kramfors",
  "kristianstad",
  "kristianstads län",
  "kristinehamn",
  "kumla",
  "kungsbacka",
  "kungälv",
  "köping",
  "laholm",
  "landskrona",
  "lidingö",
  "lidköping",
  "lindesberg",
  "linköping",
  "ljungby",
  "ludvika",
  "luleå",
  "lund",
  "kristianstads län",
  "lycksele",
  "lysekil",
  "malmö",
  "mariefred",
  "mariestad",
  "marstrand",
  "mjölby",
  "motala",
  "mölndal",
  "mönsterås",
  "nacka",
  "nora",
  "norrköping",
  "norrtälje",
  "nybro",
  "nyköping",
  "nynäshamn",
  "nässjö",
  "oskarshamn",
  "oxelösund",
  "piteå",
  "ronneby",
  "sala",
  "sandviken",
  "sigtuna",
  "simrishamn",
  "kristianstads län",
  "skanör med falsterbo stad",
  "skanör med falsterbo",
  "skara",
  "skellefteå",
  "skänninge",
  "skövde",
  "sollefteå",
  "solna",
  "stockholm",
  "strängnäs",
  "strömstad",
  "sundbyberg",
  "sundsvall",
  "säffle",
  "säter",
  "sävsjö",
  "söderhamn",
  "söderköping",
  "södertälje",
  "sölvesborg",
  "tidaholm",
  "torget",
  "torshälla",
  "tranås",
  "trelleborg",
  "trollhättan",
  "trosa",
  "kristianstads län",
  "uddevalla",
  "ulricehamn",
  "umeå",
  "uppsala",
  "vadstena",
  "varberg",
  "vaxholm",
  "vetlanda",
  "vimmerby",
  "visby",
  "kristianstads län",
  "kristianstads kommun",
  "vänersborg",
  "värnamo",
  "västervik",
  "västerås",
  "växjö",
  "ystad",
  "kristianstads län",
  "kristianstads kommun",
  "åmål",
  "älvsborg",
  "ängelholm",
  "kristianstads län",
  "örebro",
  "öregrund",
  "örnsköldsvik",
  "östersund",
  "östhammar"
]

FA_REGION = [
  "malmö",
  "lund",
  "vansbro",
  "kristianstad"
  "hässleholm",
  "ludvika",
  "karlskrona",
  "avesta",
  "hedemora",
  "älmhult",
  "osby",
  "falun",
  "borlänge",
  "ljungby",
  "mora",
  "halmstad",
  "gävle",
  "värnamo",
  "bollnäs",
  "ovanåker",
  "växjö",
  "hudiksvall",
  "kalmar",
  "ljusdal",
  "oskarshamn",
  "härjedalen",
  "västervik",
  "östersund",
  "vimmerby",
  "sundsvall",
  "jönköping",
  "kramfors",
  "borås",
  "örnsköldsvik",
  "göteborg",
  "sollefteå",
  "trollhättan",
  "vänersborg",
  "strömsund",
  "lidköping",
  "götene",
  "åsele",
  "skövde",
  "skara",
  "umeå",
  "linköping",
  "norrköping",
  "lycksele",
  "gotland",
  "vilhelmina",
  "nyköping",
  "oxelösund",
  "storuman",
  "eskilstuna",
  "skellefteå",
  "stockholm",
  "arvidsjaur",
  "västerås",
  "arjeplog",
  "örebro",
  "luleå",
  "karlskoga",
  "haparanda",
  "karlstad",
  "överkalix",
  "västlandet",
  "jokkmokk",
  "torsby",
  "gällivare",
  "malung",
  "sälen",
  "kiruna",
]

MUNICIPALITY_TO_FA = {
    "svalöv": "malmö-lund",
    "staffanstorp": "malmö-lund",
    "burlöv": "malmö-lund",
    "vellinge": "malmö-lund",
    "örkelljunga": "malmö-lund",
    "bjuv": "malmö-lund",
    "kävlinge": "malmö-lund",
    "lomma": "malmö-lund",
    "svedala": "malmö-lund",
    "skurup": "malmö-lund",
    "sjöbo": "malmö-lund",
    "hörby": "malmö-lund",
    "höör": "malmö-lund",
    "tomelilla": "malmö-lund",
    "perstorp": "malmö-lund",
    "klippan": "malmö-lund",
    "åstorp": "malmö-lund",
    "båstad": "malmö-lund",
    "malmö": "malmö-lund",
    "lund": "malmö-lund",
    "landskrona": "malmö-lund",
    "helsingborg": "malmö-lund",
    "höganäs": "malmö-lund",
    "eslöv": "malmö-lund",
    "ystad": "malmö-lund",
    "trelleborg": "malmö-lund",
    "simrishamn": "malmö-lund",
    "ängelholm": "malmö-lund",
    "sölvesborg": "kristianstad-hässleholm",
    "östra göinge": "kristianstad-hässleholm",
    "bromölla": "kristianstad-hässleholm",
    "kristianstad": "kristianstad-hässleholm",
    "hässleholm": "kristianstad-hässleholm",
    "olofström": "karlskrona",
    "karlskrona": "karlskrona",
    "ronneby": "karlskrona",
    "karlshamn": "karlskrona",
    "älmhult": "älmhult-osby",
    "osby": "älmhult-osby",
    "ljungby": "ljungby",
    "markaryd": "ljungby",
    "hylte": "halmstad",
    "halmstad": "halmstad",
    "laholm": "halmstad",
    "gnosjö": "värnamo",
    "gislaved": "värnamo",
    "värnamo": "värnamo",
    "uppvidinge": "växjö",
    "lessebo": "växjö",
    "tingsryd": "växjö",
    "växjö": "växjö",
    "torsås": "kalmar",
    "mörbylånga": "kalmar",
    "mönsterås": "kalmar",
    "emmaboda": "kalmar",
    "kalmar": "kalmar",
    "nybro": "kalmar",
    "borgholm": "kalmar",
    "högsby": "oskarshamn",
    "oskarshamn": "oskarshamn",
    "västervik": "västervik",
    "hultsfred": "vimmerby",
    "vimmerby": "vimmerby",
    "ydre": "jönköping",
    "aneby": "jönköping",
    "mullsjö": "jönköping",
    "habo": "jönköping",
    "vaggeryd": "jönköping",
    "jönköping": "jönköping",
    "nässjö": "jönköping",
    "sävsjö": "jönköping",
    "vetlanda": "jönköping",
    "eksjö": "jönköping",
    "tranås": "jönköping",
    "borås": "borås",
    "tranemo": "borås",
    "svenljunga": "borås",
    "ulricehamn": "borås",
    "falkenberg": "göteborg",
    "varberg": "göteborg",
    "kungsbacka": "göteborg",
    "härryda": "göteborg",
    "partille": "göteborg",
    "öckerö": "göteborg",
    "stenungsund": "göteborg",
    "tjörn": "göteborg",
    "orust": "göteborg",
    "ale": "göteborg",
    "lerum": "göteborg",
    "vargårda": "göteborg",
    "bollebygd": "göteborg",
    "lilla edet": "göteborg",
    "mark": "göteborg",
    "herrljunga": "göteborg",
    "göteborg": "göteborg",
    "mölndal": "göteborg",
    "kungälv": "göteborg",
    "alingssås": "göteborg",
    "sotenäs": "trollhättan-vänersborg",
    "munkedal": "trollhättan-vänersborg",
    "färgelanda": "trollhättan-vänersborg",
    "grästorp": "trollhättan-vänersborg",
    "mellerud": "trollhättan-vänersborg",
    "lysekil": "trollhättan-vänersborg",
    "uddevalla": "trollhättan-vänersborg",
    "vänersborg": "trollhättan-vänersborg",
    "trollhättan": "trollhättan-vänersborg",
    "essunga": "lidköping-götene",
    "vara": "lidköping-götene",
    "götene": "lidköping-götene",
    "lidköping": "lidköping-götene",
    "karlsborg": "skövde-skara",
    "gullspång": "skövde-skara",
    "tibro": "skövde-skara",
    "töreboda": "skövde-skara",
    "mariestad": "skövde-skara",
    "skara": "skövde-skara",
    "skövde": "skövde-skara",
    "hjo": "skövde-skara",
    "tidaholm": "skövde-skara",
    "falköping": "skövde-skara",
    "ödeshög": "linköping-norrköping",
    "kinda": "linköping-norrköping",
    "boxholm": "linköping-norrköping",
    "åtvidaberg": "linköping-norrköping",
    "finspång": "linköping-norrköping",
    "valdemarsvik": "linköping-norrköping",
    "linköping": "linköping-norrköping",
    "norrköping": "linköping-norrköping",
    "söderköping": "linköping-norrköping",
    "motala": "linköping-norrköping",
    "vadstena": "linköping-norrköping",
    "mjölby": "linköping-norrköping",
    "gotland": "gotland",
    "nyköping": "nyköping-oxelösund",
    "oxelösund": "nyköping-oxelösund",
    "vingåker": "eskilstuna",
    "katrineholm": "eskilstuna",
    "eskilstuna": "eskilstuna",
    "upplands väsby": "stockholm",
    "vallentuna": "stockholm",
    "österåker": "stockholm",
    "värmdö": "stockholm",
    "järfälla": "stockholm",
    "ekerö": "stockholm",
    "huddinge": "stockholm",
    "botkyrka": "stockholm",
    "salem": "stockholm",
    "haninge": "stockholm",
    "tyresö": "stockholm",
    "upplands-bro": "stockholm",
    "nykvarn": "stockholm",
    "täby": "stockholm",
    "danderyd": "stockholm",
    "sollentuna": "stockholm",
    "stockholm": "stockholm",
    "södertälje": "stockholm",
    "nacka": "stockholm",
    "sundbyberg": "stockholm",
    "solna": "stockholm",
    "lidingö": "stockholm",
    "vaxholm": "stockholm",
    "norrtälje": "stockholm",
    "sigtuna": "stockholm",
    "nynäshamn": "stockholm",
    "håbo": "stockholm",
    "knivsta": "stockholm",
    "heby": "stockholm",
    "tierp": "stockholm",
    "uppsala": "stockholm",
    "enköping": "stockholm",
    "östhammar": "stockholm",
    "gnesta": "stockholm",
    "flen": "stockholm",
    "strängnäs": "stockholm",
    "trosa": "stockholm",
    "skinnskatteberg": "västerås",
    "surahammar": "västerås",
    "kungsör": "västerås",
    "hallstahammar": "västerås",
    "norberg": "västerås",
    "västerås": "västerås",
    "sala": "västerås",
    "fagersta": "västerås",
    "köping": "västerås",
    "arboga": "västerås",
    "lekeberg": "örebro",
    "laxå": "örebro",
    "hallsberg": "örebro",
    "hällefors": "örebro",
    "ljusnarsberg": "örebro",
    "örebro": "örebro",
    "kumla": "örebro",
    "askersund": "örebro",
    "nora": "örebro",
    "lindesberg": "örebro",
    "degerfors": "karlskoga",
    "karlskoga": "karlskoga",
    "åmål": "karlstad",
    "kil": "karlstad",
    "storfors": "karlstad",
    "hammarö": "karlstad",
    "munkfors": "karlstad",
    "forshaga": "karlstad",
    "grums": "karlstad",
    "sunne": "karlstad",
    "karlstad": "karlstad",
    "kristinehamn": "karlstad",
    "filipstad": "karlstad",
    "hagfors": "karlstad",
    "arvika": "karlstad",
    "säffle": "karlstad",
    "tanum": "västlandet",
    "dals-ed": "västlandet",
    "bengtsfors": "västlandet",
    "strömstad": "västlandet",
    "eda": "västlandet",
    "årjäng": "västlandet",
    "torsby": "torsby",
    "malung": "malung-sälen",
    "sälen": "malung-sälen",
    "vansbro": "vansbro",
    "smedjebacken": "ludvika",
    "ludvika": "ludvika",
    "hedemora": "avesta-hedemora",
    "avesta": "avesta-hedemora",
    "gagnef": "falun-borlänge",
    "leksand": "falun-borlänge",
    "rättvik": "falun-borlänge",
    "falun": "falun-borlänge",
    "borlänge": "falun-borlänge",
    "säter": "falun-borlänge",
    "orsa": "mora",
    "älvdalen": "mora",
    "mora": "mora",
    "älvkarleby": "gävle",
    "ockelbo": "gävle",
    "hofors": "gävle",
    "gävle": "gävle",
    "sandviken": "gävle",
    "ovanåker": "bollnäs-ovanåker",
    "söderhamn": "bollnäs-ovanåker",
    "bollnäs": "bollnäs-ovanåker",
    "nordanstrig": "hudiksvall",
    "hudiksvall": "hudiksvall",
    "ljusdal": "ljusdal",
    "härjedalen": "härjedalen",
    "ragunda": "östersund",
    "bräcke": "östersund",
    "krokom": "östersund",
    "åre": "östersund",
    "berg": "östersund",
    "östersund": "östersund",
    "ånge": "sundsvall",
    "timrå": "sundsvall",
    "härnösand": "sundsvall",
    "sundsvall": "sundsvall",
    "kramfors": "kramfors",
    "örnsköldsvik": "örnsköldsvik",
    "sollefteå": "sollefteå",
    "strömsund": "strömsund",
    "dorotea": "strömsund",
    "åsele": "åsele",
    "nordmaling": "umeå",
    "bjurholm": "umeå",
    "vindeln": "umeå",
    "robertsfors": "umeå",
    "vännäs": "umeå",
    "umeå": "umeå",
    "lycksele": "lycksele",
    "malå": "lycksele",
    "villhelmina": "villhelmina",
    "storuman": "storuman",
    "skellefteå": "skellefteå",
    "norsjö": "skellefteå",
    "arvidsjaur": "arvidsjaur",
    "sorsele": "arjeplog",
    "arjeplog": "arjeplog",
    "kalix": "luleå",
    "övertorneå": "luleå",
    "älvsbyn": "luleå",
    "luleå": "luleå",
    "piteå": "luleå",
    "boden": "luleå",
    "haparanda": "haparanda",
    "överkalix": "överkalix",
    "jokkmokk": "jokkmokk",
    "gällivare": "gällivare",
    "kiruna": "kiruna",
    "pajala": "kiruna",
}

BLACKLIST = ["svenska", "engelska", "can", "design", "data", "förvaltning", "verktyg", "högskoleutbildning", "eftergymnasial utbildning", "kommunikation", "problemlösning", "tekniker", "general", "manager", "major", "mentor", "programmering", "egen bil", "barn", "back end", "front end", "not", "projektledning", "eftergymnasial utbildning", "miljö", "körkort", "leverantörer", "script", "stack", "Svenskt medborgarskap", "affärssystem", "budget", "sales", "religion", "client", "tekniker", "ingenjör", "personalansvarig", "project manager", "arkitekt", "förvaltare", "traffic", "diskrimineringsombudsman", "arbetslivserfarenhet"]
